name: Generate matrix

description: Generate a build matrix

inputs:
  matrix:
    description: YAML string
    required: true

outputs:
  json:
    description: JSON string
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - id: matrix
      shell: bash
      run: |
        echo '::group::Format matrix to json'
        cat <<'EOT' | ruby
        require 'json'
        require 'yaml'
        matrix = YAML.load DATA.read
        puts "::set-output name=matrix::#{JSON.generate matrix}"
        __END__
        ${{ inputs.matrix }}
        EOT
        echo '::endgroup::'
