language: c

compiler:
  - clang

env:
  global:
    - FOO=foo BAR=bar
    - HOMEBREW_NO_AUTO_UPDATE=1
  # matrix:
  #   - TEST=test1
  #   - TEST=test2

_anchors:
  apt: &apt
    addons:
      apt:
        packages:
          - gdb

  homebrew: &homebrew
    addons:
      homebrew:
        packages:
          - google-perftools
        #   - python
        # brewfile: Brewfile.travis
        # update: true

  caches: &cache
    cache:
      directories:
        # - /usr/local/Homebrew/Library/Homebrew/vendor/
        # - /usr/local/Homebrew/Library/Taps/
        - ${TRAVIS_BUILD_DIR}/build

  envs:
    - &myfoo
      MYFOO=myfoo
    - &mybar
      MYBAR=mybar

  linux_script: &linux-script
    - gcc -g3 -O0 -o main main.c
    - ./main localhost

  osx_script: &osx-script
    - git clone --depth 1 https://github.com/ichizok/vim-perf /tmp/vim-perf
    - cd /tmp/vim-perf
    - make
    - cd -
    - git clone --depth 1 https://github.com/vim/vim /tmp/vim
    - cd /tmp/vim
    - ./configure --with-features=huge --disable-nls --enable-fail-if-missing
    - sed -i.bak -f config.mk.sed src/auto/config.mk
    - make -j$(getconf _NPROCESSORS_ONLN 2>/dev/null)
    - cd -
    - cp /tmp/vim/src/vim .
    - ./vim -u NONE -i NONE --not-a-term -N -V1 -S test.vim +"sleep 1" +"call Estimate(3000, '1m')" +"qall!"
    - ./vim -u NONE -i NONE --not-a-term -N -V1 -S test.vim +"sleep 1" +"call Estimate(300, '10m')" +"qall!"
    - ./vim -u NONE -i NONE --not-a-term -N -V1 -S test.vim +"sleep 1" +"call Estimate(30, '100m')" +"qall!"
    - ./vim -u NONE -i NONE --not-a-term -N -V1 -S test.vim +"sleep 1" +"call Estimate(3, '1000m')" +"qall!"
    - ./vim -u NONE -i NONE --not-a-term -N -V1 +"call writefile(systemlist('vimmap '..getpid()), 'vim.map')" +"q"
    - tar -czf vim-prof.tgz vim *.out vim.map

jobs:
  include:
    # - stage: test
    #   name: Test on Linux - trusty (amd64)
    #   os: linux
    #   dist: trusty
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - xenial (amd64)
    #   os: linux
    #   dist: xenial
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - bionic (amd64)
    #   os: linux
    #   dist: bionic
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - trusty (ppc64le)
    #   os: linux
    #   dist: xenial
    #   arch: ppc64le
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - xenial (ppc64le)
    #   os: linux
    #   dist: xenial
    #   arch: ppc64le
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - bionic (ppc64le)
    #   os: linux
    #   dist: bionic
    #   arch: ppc64le
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - trusty (s390x)
    #   os: linux
    #   dist: trusty
    #   arch: s390x
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - xenial (s390x)
    #   os: linux
    #   dist: xenial
    #   arch: s390x
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - bionic (s390x)
    #   os: linux
    #   dist: bionic
    #   arch: s390x
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - trusty (arm64)
    #   os: linux
    #   dist: trusty
    #   arch: arm64
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - xenial (arm64)
    #   os: linux
    #   dist: xenial
    #   arch: arm64
    #   script: *linux-script
    # - stage: test
    #   name: Test on Linux - bionic (arm64)
    #   os: linux
    #   dist: bionic
    #   arch: arm64
    #   script: *linux-script
    # - stage: test
    #   name: Test on El Capitan
    #   os: osx
    #   osx_image: xcode7.3
    #   env:
    #     - *myfoo
    #     - *mybar
    #   script: *osx-script
    #   after_script:
    #     - echo "after_script done"
    # - stage: test
    #   name: Test on Sierra
    #   os: osx
    #   osx_image: xcode8.3
    #   script: *osx-script
    # - stage: test
    #   name: Test on High Sierra
    #   os: osx
    #   osx_image: xcode9.4
    #   script: *osx-script
    - stage: test
      name: Test on Mojave
      os: osx
      osx_image: xcode11.3
      <<: *homebrew
      # <<: *cache
      script: *osx-script
      deploy:
        provider: releases
        token:
          secure: f96CLQZZCYIJ5TY2os6IHHbL2U2Jzx+tgh8+8m3Xsf65WeFNHreLKMYjyVhz70KSx4DrUxs6XpOoBdgmeue/5c+1IvXZkUFt6OL32a8MU07y2dPKAi69RMa/BA4i0wTtDmFKAKGxgT5klM2XOiCjchsiKuji7yDk3zX0RpbKP8cwnpZK+OH2TcOT3P1L+zaGZtlTmgmni3QSZieLQlAoUelYsy3KJmNKM2DF+n9iiOoFeY3OCMizFNKe0XjRkc90xDNcQdHnuzxAb4lPrQK1dy+w7niguiyUHwzu99vHc/ltm/mU/YQi3ZRma7gklj8/xSWArNqd0WfcAZZ+n5f4J5bnBY6gwinVCRYuTETlt+E6xcArUBl0ylRw8ee7JxIn60m2zIxl7LOgZEgijD4VvrFoExN36BE4KkccBqzjr3CFyAQzD0D326cLzmHTbp00IoVZgi8C40BakkQAAw22vI0PKc6jbfo/HIznQhCk9NnByiNtTnjb+UAB6wxxjiEI1DNj1XPEHQtOBvWMthEL3RD5SVbHIm7MiDEcB7U8c6dLZdUC7jYFUKVHJbd43MPgoOU49aMVeZqYX0nlX86lQoh24TY8yR7NPxt9LtuMwQZSNO8++lMW2F0APDwjIa1wXxmLTG4Pan/oQ7VLtffPGm9oi53nZBszpOeubdzDRnU=
        file: vim-prof.tgz
        skip_cleanup: true
    # - stage: deploy
    #   name: Deployment
    #   os: linux
    #   dist: bionic
    #   arch: amd64
    #   script: skip
    #   # <<: *cache
    #   before_deploy: ls -al *
    #   deploy:
    #     provider: releases
    #     token:
    #       secure: f96CLQZZCYIJ5TY2os6IHHbL2U2Jzx+tgh8+8m3Xsf65WeFNHreLKMYjyVhz70KSx4DrUxs6XpOoBdgmeue/5c+1IvXZkUFt6OL32a8MU07y2dPKAi69RMa/BA4i0wTtDmFKAKGxgT5klM2XOiCjchsiKuji7yDk3zX0RpbKP8cwnpZK+OH2TcOT3P1L+zaGZtlTmgmni3QSZieLQlAoUelYsy3KJmNKM2DF+n9iiOoFeY3OCMizFNKe0XjRkc90xDNcQdHnuzxAb4lPrQK1dy+w7niguiyUHwzu99vHc/ltm/mU/YQi3ZRma7gklj8/xSWArNqd0WfcAZZ+n5f4J5bnBY6gwinVCRYuTETlt+E6xcArUBl0ylRw8ee7JxIn60m2zIxl7LOgZEgijD4VvrFoExN36BE4KkccBqzjr3CFyAQzD0D326cLzmHTbp00IoVZgi8C40BakkQAAw22vI0PKc6jbfo/HIznQhCk9NnByiNtTnjb+UAB6wxxjiEI1DNj1XPEHQtOBvWMthEL3RD5SVbHIm7MiDEcB7U8c6dLZdUC7jYFUKVHJbd43MPgoOU49aMVeZqYX0nlX86lQoh24TY8yR7NPxt9LtuMwQZSNO8++lMW2F0APDwjIa1wXxmLTG4Pan/oQ7VLtffPGm9oi53nZBszpOeubdzDRnU=
    #     file: 'main'
    #     # provider: script
    #     # script: ls -al *
    #     cleanup: false
    #     on:
    #       # condition: $TRAVIS_OSX_IMAGE = xcode10.2
    #       all_branches: true
    #       # tags: true
    #       repo: ichizok/travis-playground

# vim:set sts=2 sw=2 tw=0 et:
