name: Test actions/github-script

description: Test actions/github-script

runs:
  using: "composite"
  steps:
    - name: use github-script
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: exec-script
      with:
        script: return "hello!"
        result-encoding: string

    - name: Show result
      shell: bash
      env:
        RESULT: ${{ steps.exec-script.outputs.result }}
      run: echo "${RESULT}"
