# name: GitHub CI
# 
# on: [ push, workflow_dispatch ]
# 
# env:
#   VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
# 
# jobs:
#   build:
#     runs-on: windows-latest
# 
#     strategy:
#       matrix:
#         toolchain: [msvc, mingw]
#         arch: [x64, x86]
#         include:
#           - arch: x64
#             vcarch: amd64
#             msystem: MINGW64
#           - arch: x86
#             vcarch: x86
#             msystem: MINGW32
# 
#     steps:
#     - name: Initalize
#       id: init
#       shell: bash
#       run: |
#         git config --global core.autocrlf input
# 
#     - uses: msys2/setup-msys2@v2
#       if: matrix.toolchain == 'mingw'
#       with:
#         msystem: ${{ matrix.msystem }}
#         release: false
# 
#     - uses: actions/checkout@v2
# 
#     - name: Build (MSVC)
#       if: matrix.toolchain == 'msvc'
#       shell: cmd
#       run: |
#         call "%VCVARSALL%" ${{ matrix.vcarch  }}
#         cl stack.c /link /out:stack.exe
# 
#     - name: Build (MinGW)
#       if: matrix.toolchain == 'mingw'
#       shell: msys2 {0}
#       run: |
#         gcc -o stack.exe stack.c
# 
#     - name: Test
#       shell: cmd
#       timeout-minutes: 20
#       run: |
#         stack.exe
