name: GitHub CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # generate-matrix:
  #   runs-on: ubuntu-latest
  # 
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  # 
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: set-matrix
  #       uses: ./.github/actions/generate-matrix
  #       with:
  #         matrix: |
  #           os:
  #             - ubuntu-latest
  #             - macos-latest
  #           compiler:
  #             - clang
  #             - gcc
  #           include:
  #             - os: macos-10.15
  #               compiler: clang
  #             - os: macos-latest
  #               compiler: clang
  #               post: true
  # 
  # trial-matrix:
  #   needs: generate-matrix
  # 
  #   runs-on: ${{ matrix.os }}
  # 
  #   strategy:
  #     fail-fast: true
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
  # 
  #   steps:
  #     - name: Show strategy
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(strategy) }}
  #         EOT
  # 
  #     - name: Show matrix
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(matrix) }}
  #         EOT
  # 
  #     - name: Show post
  #       run: |
  #         : "post: ${{ matrix.post }}"

  # trial-gh:
  #   runs-on: ubuntu-latest
  # 
  #   steps:
  #     - name: Show context
  #       run: |
  #         (
  #         echo "github.event_name=${{ github.event_name }}"
  #         echo "${{ toJSON(github.event) }}"
  #         ) || true
  # 
  #     - uses: actions/checkout@v2
  # 
  #     - name: Commit
  #       if: github.ref_name == 'master'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         grep -qv hello dir/sample.txt
  #         echo hello >> dir/sample.txt
  #         git config --local user.name 'github-actions[bot]'
  #         git config --local user.email 'github-actions[bot]@users.noreply.github.com'
  #         git switch -c trial/gh
  #         git add dir/sample.txt
  #         git commit -m 'Add message'
  #         git push -u origin trial/gh
  # 
  #     - name: Create pull request
  #       if: github.ref_name == 'master'
  #       id: pull_request
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         cat << EOT > /tmp/message
  #         ### Test
  # 
  #         * message 1
  #         * message 2
  #         EOT
  #         gh pr create --base master --title 'trial: Add message' --body-file /tmp/message | tee /tmp/pull_request
  #         echo "::set-output name=url::$(cat /tmp/pull_request)"
  # 
  #     - name: Merge pull request
  #       if: github.ref_name == 'master'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         gh pr merge ${{ steps.pull_request.outputs.url }} --auto --merge --delete-branch

  trial-bm:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Benchmark by Vim
        run: |
          echo;echo 'Trial #1'
          vim -u NONE -esNX -V1 -S test.vim -c q
          echo;echo 'Trial #2'
          vim -u NONE -esNX -V1 -S test.vim -c q
          echo;echo 'Trial #3'
          vim -u NONE -esNX -V1 -S test.vim -c q

      - name: Benchmark by Python
        run: |
          echo;echo 'Trial #1'
          python3 test.py
          echo;echo 'Trial #2'
          python3 test.py
          echo;echo 'Trial #3'
          python3 test.py
