name: GitHub CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # generate-matrix:
  #   runs-on: ubuntu-latest
  # 
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  # 
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: set-matrix
  #       uses: ./.github/actions/generate-matrix
  #       with:
  #         matrix: |
  #           os:
  #             - ubuntu-latest
  #             - macos-latest
  #           compiler:
  #             - clang
  #             - gcc
  #           include:
  #             - os: macos-10.15
  #               compiler: clang
  #             - os: macos-latest
  #               compiler: clang
  #               post: true
  # 
  # trial-matrix:
  #   needs: generate-matrix
  # 
  #   runs-on: ${{ matrix.os }}
  # 
  #   strategy:
  #     fail-fast: true
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
  # 
  #   steps:
  #     - name: Show strategy
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(strategy) }}
  #         EOT
  # 
  #     - name: Show matrix
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(matrix) }}
  #         EOT
  # 
  #     - name: Show post
  #       run: |
  #         : "post: ${{ matrix.post }}"

  trial-gh:
    runs-on: ubuntu-latest

    # if: github.ref == 'refs/heads/master' && github.sender.login != 'github-actions[bot]'

    steps:
      - name: Show context
        run: |
          (
          echo "github.event_name=${{ github.event_name }}"
          echo "${{ toJSON(github.event) }}"
          ) || true

      - name: Commit
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo hello >> dir/sample.txt
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git switch -c trial/gh
          git add dir/sample.txt
          git commit -m 'Add message'
          git push -u origin trial/gh

      # - name: Create pull request
      #   id: pull_request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr create --base master --title 'trial: Add message' --body "### Test\n\n* message1\n*message2" | tee .pull_request
      #     echo "::set-output name=url::value=$(cat .pull_request)"
      # 
      # - name: Merge pull request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr merge ${{ steps.pull_request.outputs.url }} --auto --merge --delete-branch
