name: GitHub CI

on: [ push, workflow_dispatch ]

jobs:
  # generate-matrix:
  #   runs-on: ubuntu-latest
  # 
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  # 
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: set-matrix
  #       uses: ./.github/actions/generate-matrix
  #       with:
  #         matrix: |
  #           os:
  #             - ubuntu-latest
  #             - macos-latest
  #           compiler:
  #             - clang
  #             - gcc
  #           include:
  #             - os: macos-10.15
  #               compiler: clang
  #             - os: macos-latest
  #               compiler: clang
  #               post: true
  # 
  # trial-matrix:
  #   needs: generate-matrix
  # 
  #   runs-on: ${{ matrix.os }}
  # 
  #   strategy:
  #     fail-fast: true
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
  # 
  #   steps:
  #     - name: Show strategy
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(strategy) }}
  #         EOT
  # 
  #     - name: Show matrix
  #       run: |
  #         cat <<'EOT' | jq -r .
  #         ${{ toJSON(matrix) }}
  #         EOT
  # 
  #     - name: Show post
  #       run: |
  #         : "post: ${{ matrix.post }}"

  trial-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04

    steps:
      - name: Show Installed packages
        run: dpkg -l
