name: GitHub CI

on: [ push, workflow_dispatch ]

jobs:
  trial:
    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        features: [tiny, normal, huge]
        compiler: [gcc, clang]
        extra: [none]
        include:
          - os: ubuntu-18.04
            features: tiny
            compiler: gcc
            test: testtiny
            extra: nogui
          - os: ubuntu-18.04
            features: tiny
            compiler: clang
            test: testtiny
            extra: nogui
          - os: ubuntu-18.04
            features: huge
            compiler: clang
            test: scripttests
            coverage: true
          - os: ubuntu-18.04
            features: huge
            compiler: gcc
            test: scripttests test_libvterm
            coverage: true
          - os: ubuntu-18.04
            features: huge
            compiler: gcc
            test: -C testgui
            coverage: true
            extra: testgui
          - os: ubuntu-18.04
            features: huge
            compiler: gcc
            extra: unittests
          - os: ubuntu-18.04
            features: huge
            compiler: clang-11
            extra: asan
        exclude:
          - os: macos-10.15
            features: tiny
          - os: macos-10.15
            features: normal
          - os: macos-10.15
            features: huge
            compiler: gcc

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test 1
        uses: ./.github/actions/test

      - name: Test 2
        uses: ./.github/actions/test
        with:
          nice-input: 'Nice!!'

      - name: Test 3
        run: |
          (
          echo "FOO=123 456"
          echo "BAR=999 999"
          ) >> $GITHUB_ENV

      - name: Check variables
        run: |
          echo "matrix:"
          echo "  os       = ${{ matrix.os }}"
          echo "  features = ${{ matrix.features }}"
          echo "  compiler = ${{ matrix.compiler }}"
          echo "  test     = ${{ matrix.test }}"
          echo "  nogui    = ${{ matrix.nogui }}"
          echo "  coverage = ${{ matrix.coverage }}"
          echo "  asan     = ${{ matrix.asan }}"
          echo "extra:"
          echo "  NICE_INPUT=${NICE_INPUT}"
          echo "  FOO=${FOO}"
          echo "  BAR=${BAR}"

      - name: Function
        run: |
          echo "1: ################"
          if ${{ startsWith(matrix.os, 'ubuntu-') }}; then
            echo "Ubuntu!!"
          fi
          echo "2: ################"
          if ${{ startsWith(matrix.os, 'macos-') }}; then
            echo "macOS!!"
          fi
          echo "3: ################"
          if ${{ matrix.coverage == true }}; then
            echo "coverage"
          else
            echo "w/o coverage"
          fi

      - name: Run Ubuntu
        if: matrix.os == 'ubuntu-18.04'
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"

      - name: Run macOS
        if: matrix.os == 'macos-10.15'
        run: |
          sudo xcode-select -s /Applications/Xcode_12.2.app
          xcodebuild -showsdks || true
          # xcrun --show-sdk-platform-path || true
          # xcrun --show-sdk-platform-version || true
          xcrun --sdk macosx11.0 cc -arch x86_64 -arch arm64e -o test.out main.c
          file test.out
          otool -L test.out
